### GET product
GET http://localhost:8081/api/v2/product HTTP/1.1


### Get Product with Token
GET http://localhost:8081/api/v2/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjI5NzY2NDYsImlkIjoxLCJsZXZlbCI6IiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.-Pht2qskQQoOn35UTDyX06BCJGFaE_lBDgVDyMWaGrM

### Create product
POST http://localhost:8081/api/v2/product HTTP/1.1
Content-Type: application/json

{
    "username":"admin",
    "password":"1234"
}
